DESCRIPTION = "An implementation of RFC 7049 - Concise Binary Object Representation (CBOR)."
HOMEPAGE = "https://bitbucket.org/bodhisnarkva/cbor"
LICENSE = "CLOSED"
#LICENSE = "Apache-2.0"
#LIC_FILES_CHKSUM = "file://LICENSE;md5=97c0bda20ad1d845c6369c0e47a1cd98"

SRC_URI[md5sum] = "22b03b59784fd78cb6c27aa498af0db6"
SRC_URI[sha256sum] = "13225a262ddf5615cbd9fd55a76a0d53069d18b07d2e9f19c39e6acb8609bbb6"

inherit pypi
