DESCRIPTION = "A portable, lightweight MessagePack serializer and deserializer written in pure Python."
HOMEPAGE = "https://github.com/vsergeev/u-msgpack-python"
LICENSE = "MIT"
LIC_FILES_CHKSUM = "file://LICENSE;md5=dd8d2daf6a42bad469f04d7e8f4647fb"

SRC_URI[md5sum] = "8c2a628b26f7e2d5857fdddeca8478a0"
SRC_URI[sha256sum] = "2f31fc1b6dd8632c230ea7012470e40f77119f20999274dda6f1afa9c305e590"

inherit pypi
